Updated app for enonicXp v7.12.x anf react4xp v4.1.0
GravitonDigital/feature-toggle-app pull request #26
Opened 2023-09-07 09:03 UTC by annesiri

Updated npm packages to make feature toggle app work with react4xp v4.1.0 and enonicXp v7.12.0 (to make it work in SSB's enonic environment). 

Notable changes: 
* updated react4xp
* updated to React 18
* changed material ui packages to be compatible with react 18
* updated webpack

2023-09-07 09:05 UTC, omsaggau commented on build.gradle
> +    systemVersion = "${xpVersion}"}
📐

2023-09-07 09:08 UTC, omsaggau commented on package.json
> +    "build:react4xp": "npm explore @enonic/react4xp R4X_APP_NAME=com.gravitondigital.featuretoggle R4X_DIR_PATH_ABSOLUTE_PROJECT=$INIT_CWD -- npm run build:react4xp"
Denne kan endres til å bare være `npm explore @enonic/react4xp -- npm run build:react4xp `

2023-09-14 06:58 UTC, tajakobsen requested changes
Very good job! 

The only problem is that I'm having problems building it, because I can't find Linux bindings for the deprecated *node-sass*-package. Can you replace it with the *sass*-package. *sass-loader* will work with either.

2023-09-14 06:58 UTC, tajakobsen commented on package.json
> +    "node-sass": "^9.0.0",
`node-sass` has been deprecated, and I'm not able to build this project on Linux. Can you replace it with the `sass` package?

```suggestion
    "sass": "^1.67.0",
```

2023-09-14 12:20 UTC, tajakobsen approved these changes
Looks good. Merging to main.

2023-09-14 12:21 UTC, merged